import './fonts.css'
import Providers from "@/app/providers";
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (<html lang="en">
  <body className="w-full m-0 p-0">
  <Providers>{children}</Providers>
  </body>
  </html>);
}
